### test word
GET http://127.0.0.1:8000/text/word


### test setence
GET http://127.0.0.1:8000/text/sentence


### test paragraph
GET http://127.0.0.1:8000/text/paragraph


### test 10 words
GET http://127.0.0.1:8000/text/words/10


### test 5 setences
GET http://127.0.0.1:8000/text/sentences/5


### test 3 paragraphs
GET http://127.0.0.1:8000/text/paragraphs/3

### test 0 words
GET http://127.0.0.1:8000/text/words/0


### test 0 setences
GET http://127.0.0.1:8000/text/sentences/0


### test 101 paragraphs
GET http://127.0.0.1:8000/text/paragraphs/101

### test 101 words
GET http://127.0.0.1:8000/text/words/101


### test 101 setences
GET http://127.0.0.1:8000/text/sentences/101


### test 101 paragraphs
GET http://127.0.0.1:8000/text/paragraphs/101


### test 0 array of boolean
GET http://127.0.0.1:8000/json/array/boolean?len=0


### test 10 array of boolean
GET http://127.0.0.1:8000/json/array/boolean?len=10


### test 101 array of boolean
GET http://127.0.0.1:8000/json/array/boolean?len=101