### test -1 words
GET http://127.0.0.1:8000/text/word?amount=-1


### test -1 setences
GET http://127.0.0.1:8000/text/sentence?amount=-1


### test -1 paragraphs
GET http://127.0.0.1:8000/text/paragraph?amount=-1

### test word
GET http://127.0.0.1:8000/text/word


### test setence
GET http://127.0.0.1:8000/text/sentence


### test paragraph
GET http://127.0.0.1:8000/text/paragraph


### test 10 words
GET http://127.0.0.1:8000/text/word?amount=10


### test 5 setences
GET http://127.0.0.1:8000/text/sentence?amount=5


### test 3 paragraphs
GET http://127.0.0.1:8000/text/paragraph?amount=3

### test 0 words
GET http://127.0.0.1:8000/text/word?amount=0


### test 0 setences
GET http://127.0.0.1:8000/text/sentence?amount=0


### test 0 paragraphs
GET http://127.0.0.1:8000/text/paragraph?amount=0


### test 101 words
GET http://127.0.0.1:8000/text/word?amount=101


### test 101 setences
GET http://127.0.0.1:8000/text/sentence?amount=101


### test 101 paragraphs
GET http://127.0.0.1:8000/text/paragraph?amount=101


### register
POST http://127.0.0.1:8000/jwt/register
Content-Type: application/json

{
    "username": "ilfey",
    "email": "ilfey.global@example.com",
    "password": "QWEasd123"
}


### login
POST http://127.0.0.1:8000/jwt/login
Content-Type: application/json

{
    "username": "ilfey",
    "password": "QWEasd123"
}


### private word
POST http://127.0.0.1:8000/private/text/word
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NjkyOTgyNDYuNTk5NjIxLCJpYXQiOjE2NjkyMTE4NDYuNTk5NjIxLCJ1c2VybmFtZSI6ImlsZmV5In0.J-fqy78OtdFqH-xQ1I4a0ST8CZ00qjpGAvr457dR8MQ
